@host = http://localhost
@port = 5000
@token = eyJhbGciOiJIUzI1NiJ9.LGZsZnplbWxmemUsZm1lbA.SS8RtrNp0MAgIFX8ueSp1WzlND99lGyo4tPDsghd3P0
@feature = candidate

### Create new record
POST {{host}}:{{port}}/api/{{feature}}/create-one
token: Bearer {{token}}
Content-Type: application/json

{
    "firstName": "firstName1",
    "lastName": "lastName1",
    "address": "address1",
    "postalCode": "postalCode1",
    "phoneNumber": 123456789,
    "email": "ddddeed",
    "degree": "degree1",
    "dateOfBirth": "2021-07-20",
    "placeOfBirth": "placeOfBirth1",
    "candidateCv": "candidateCv1",
    "recruitmentNumber": 2,
    "userNumber" : 1
}

### Get one record by id
GET {{host}}:{{port}}/api/{{feature}}/get-one-by-id/64f5d6a71c7034a3fbd81a1e
token: Bearer {{token}}

### Update one record by id
PUT {{host}}:{{port}}/api/{{feature}}/update-one-by-id/64f5d6a71c7034a3fbd81a1e
token: Bearer {{token}}
Content-Type: application/json

{
    "firstName": "Nassim",
    "status": "Pending"
}

### Delete one record by id
DELETE  {{host}}:{{port}}/api/{{feature}}/delete-one-by-id/64f5078d33de1d019a4e7ae0
token: Bearer {{token}}

### Get many record
GET {{host}}:{{port}}/api/{{feature}}/get-many
token: Bearer {{token}}
Content-Type: application/json

{

}

### Delete many records by ids
DELETE  {{host}}:{{port}}/api/{{feature}}/delete-many-by-ids
token: Bearer {{token}}
Content-Type: application/json

{
    "ids": ["64f5f6e40d878249d3256b14"]
}
