@host = http://localhost
@port = 5000
@token = eyJhbGciOiJIUzI1NiJ9.LGZsZnplbWxmemUsZm1lbA.SS8RtrNp0MAgIFX8ueSp1WzlND99lGyo4tPDsghd3P0
@feature = interview

### Create new record
POST {{host}}:{{port}}/api/{{feature}}/create-one
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "recruitmentNumber" : 1,
    "evaluatorNumber" : 5,
    "candidateNumber" : 14,
    "interviewDate": "2021-07-20T20:00"
}

### Get one record by id
GET {{host}}:{{port}}/api/{{feature}}/get-one-by-id/64f777d652f671919206d301
Authorization: Bearer {{token}}

### Update one record by id
PUT {{host}}:{{port}}/api/{{feature}}/update-one-by-id/64f777d652f671919206d301
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "interviewDate": "2022-07-20T20:00",
    "evaluatorNumber": 3
}

### Delete one record by id
DELETE  {{host}}:{{port}}/api/{{feature}}/delete-one-by-id/64f7721f66adf2b4fae7eca5
Authorization: Bearer {{token}}

### Get many record
GET {{host}}:{{port}}/api/{{feature}}/get-many?minEvaluatorNumber=3&maxEvaluatorNumber=3
Authorization: Bearer {{token}}
Content-Type: application/json

{

}

### Delete many records by ids
DELETE  {{host}}:{{port}}/api/{{feature}}/delete-many-by-ids
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "ids": ["64dcdfcf641ab6724e95c726"]
}
