@host = http://localhost
@port = 5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZjRjYjE3YzI4NDg2MDczNDRlNjI5MCIsInJvbGUiOiJBZG1pbmlzdHJhdG9yIiwiaWF0IjoxNjkzNzY0NzA2LCJleHAiOjE2OTM3NjgzMDZ9.Za-zvZfL6PA31_nqvPkFfNon8QQgtjLWcKl6ffKljKI
@feature = user
######################################
########    Login of user
######################################
POST {{host}}:{{port}}/api/{{feature}}/login
token: Bearer {{token}}
Content-Type: application/json

{
    "email": "zibi@example.com",
    "password": "example+123"
}

######################################
########    Register of candidate
######################################
POST {{host}}:{{port}}/api/{{feature}}/register
Content-Type: application/json

{
    "firstName": "First Name",
    "lastName": "Last Name",
    "email": "hamza@example.com",
    "password": "example+123"
}

######################################
########    Create new user
######################################
POST {{host}}:{{port}}/api/{{feature}}/create-one
token: Bearer {{token}}
Content-Type: application/json

{
    "firstName": "First Name",
    "lastName": "Last Name",
    "email": "vkkkvk@example.com",
    "password": "example+123",
    "department": "Department",
    "role" : "Administrator"
}

######################################
########    Get one user by id
######################################
GET {{host}}:{{port}}/api/{{feature}}/get-one-by-id/64f4cd1bb73552d72e65166c
token: Bearer {{token}}

######################################
########    Update one user by id
######################################
PUT {{host}}:{{port}}/api/{{feature}}/update-one-by-id/64f4cd1bb73552d72e65166c
token: Bearer {{token}}
Content-Type: application/json

{
    "status": "Approved"
}

######################################
########    Delete one user by id
######################################
DELETE  {{host}}:{{port}}/api/{{feature}}/delete-one-by-id/64f4cd1bb73552d72e65166c
token: Bearer {{token}}

######################################
########    Get many user by filter
######################################
GET {{host}}:{{port}}/api/{{feature}}/get-many
token: Bearer {{token}}
Content-Type: application/json

{
    "firstName": "",
    "lastName": "",
    "department": "",
    "email": "",
    "role" : "Candidate",
    "status" : "Pending"
}

######################################
########    Delete many user by ids
######################################
DELETE  {{host}}:{{port}}/api/{{feature}}/delete-many-by-ids
token : Bearer {{token}}
Content-Type: application/json

{
    "ids": ["64f4c44f183a815a2cc2a07c"]
}


